import {createApi, fetchBaseQuery} from '@reduxjs/toolkit/query/react'

const USER_API='http://localhost:8080/app/api/v1/';


export const appApi = createApi({
    reducerPath:"api",
    baseQuery:fetchBaseQuery({baseUrl:USER_API,credentials:"include"}),
    endpoints:(build)=>({
        createMovie:build.mutation({
            query:({formData})=>({
                url:"/movie",
                method:"POST",
                body:formData,
            })
        }),
        getAllMovies:build.query({
            query:()=>({
                url:'/movie/all',
                method:"GET"
            })
        }),
        getMovieById:build.query({
            query:({id})=>({
                url:`/movie/${id}`,
                method:"GET",
                credentials:"include"
            })
        }),
        getRecommendedMovies:build.query({
            query:()=>({
                url:'/movie/recommended',
                method:"GET"
            })
        }),
        createTheater:build.mutation({
            query:({formData})=>({
                url:'/theater',
                method:"POST",
                body:formData
            })
        }),
        getAllTheaters:build.query({
            query:()=>({
                url:"/theater/all",
                method:"GET"
            })
        }),
        getTheaterByState:build.query({
            query:({state})=>({
                url:`/theater/theaters?state=${state}`,
                method:"GET",
            })
        }),
        createShow:build.mutation({
            query:({formData})=>({
                url:'/show/',
                method:"POST",
                body:formData,
                credentials:"include"
            })
        }),
        getShowById:build.query({
            query:({id})=>({
                url:`/show/${id}`,
                method:'GET'
            })
        }),
        updateSeatStatus:build.mutation({
            query:({showId,formData})=>({
                url:`/show/${showId}`,
                method:"PUT",
                body:formData
            })
        }),
        getShowByMovieAndLocation:build.query({
            query:({movieId,date,location})=>({
                url: `/show/movie/${movieId}?date=${date}&location=${location}`,
                method:"GET",
                credentials:"include"
            })
        }),
        getOtpByEmail:build.mutation({
            query:({email})=>({
                url:'/auth/send-otp',
                method:"POST",
                body:{email},
                credentials:"include"
            })
        }),
        verifyEmail:build.mutation({
            query:({hash,otp,email})=>({
                url:'/auth/verify-otp',
                method:"POST",
                body:{hash,otp,email},
                credentials:"include"
            })
        }),
        activateUser:build.mutation({
            query:({id,userStatus})=>({
                url:`/user/activate/${id}`,
                method:"POST",
                body:{userStatus},
                credentials:'include'
            })
        }),
        logout:build.query({
            query:({})=>({
                url:"/auth/logout",
                method:'POST'
            })
        }),
        createUser:build.mutation({
            query:({name,email,phone})=>({
                url:'/user',
                method:"POST",
                body:{name,email,phone},
                credentials:'include'
            })
        }),
        findUserByEmail:build.mutation({
            query:({email})=>({
                url:'/user/email',
                method:"POST",
                body:{email},
                credentials:'include'
            })
        })
    }), 
})


export const {
    useCreateMovieMutation,
    useGetAllMoviesQuery,
    useGetMovieByIdQuery,
    useGetRecommendedMoviesQuery,
    useCreateTheaterMutation,
    useGetAllTheatersQuery,
    useGetTheaterByStateQuery,
    useCreateShowMutation,
    useGetShowByMovieAndLocationQuery,
    useGetShowByIdQuery,
    useUpdateSeatStatusMutation,
    useGetOtpByEmailMutation,
    useLogoutQuery,
    useActivateUserMutation,
    useVerifyEmailMutation,
    useCreateUserMutation,
    useFindUserByEmailMutation
}=appApi; 